=head1 NAME

Test.Class - xUnit-style testing framework for Lua.

=head1 SYNOPSIS

  -- Test class for My.Class

  -- t/lib/TestsFor/My/Class.lua
  local _M = require('Test.Class')('TestsFor.My.Class')

  _M:test_sum()
    is(sum(2, 2), 4, '2+2 is 4')
    is(sum(2.00001, 1.99999), 4, '2.00001 + 1.99999 is also 4')
  end

  return _M

  -- Loading test classes directly...

  -- t/unit.lua
  -- ...considering that path/to/t/lib/?.lua is in package.path...
  require('TestsFor.My.Class')
  local TC = require('Test.Class')
  TC.runtests()

  -- ...or, using a loader

  -- t/unit.lua
  local TC = require('Test.Class')

  -- Load test classes from ./t/lib
  TC.load_classes('./t/lib')

  -- Run loaded tests
  TC.run_tests()

=head1 DESCRIPTION

Interface can be unstable - use at your own risk.

=head1 SEE ALSO

=over

=item L<xUnit|https://wikipedia.org/wiki/XUnit>

=item L<Test::Class::Moose|https://metacpan.org/pod/Test::Class::Moose>

=back

=head1 LICENSE

MIT/X11

=head1 AUTHOR

L<Ilya Chesnokov|https://github.com/ichesnokov>

=cut
