local lu = require("luaucdn")

-- Bidi_Class values
lu.UCDN_BIDI_CLASS_L = 0
lu.UCDN_BIDI_CLASS_LRE = 1
lu.UCDN_BIDI_CLASS_LRO = 2
lu.UCDN_BIDI_CLASS_R = 3
lu.UCDN_BIDI_CLASS_AL = 4
lu.UCDN_BIDI_CLASS_RLE = 5
lu.UCDN_BIDI_CLASS_RLO = 6
lu.UCDN_BIDI_CLASS_PDF = 7
lu.UCDN_BIDI_CLASS_EN = 8
lu.UCDN_BIDI_CLASS_ES = 9
lu.UCDN_BIDI_CLASS_ET = 10
lu.UCDN_BIDI_CLASS_AN = 11
lu.UCDN_BIDI_CLASS_CS = 12
lu.UCDN_BIDI_CLASS_NSM = 13
lu.UCDN_BIDI_CLASS_BN = 14
lu.UCDN_BIDI_CLASS_B = 15
lu.UCDN_BIDI_CLASS_S = 16
lu.UCDN_BIDI_CLASS_WS = 17
lu.UCDN_BIDI_CLASS_ON = 18
lu.UCDN_BIDI_CLASS_LRI = 19
lu.UCDN_BIDI_CLASS_RLI = 20
lu.UCDN_BIDI_CLASS_FSI = 21
lu.UCDN_BIDI_CLASS_PDI = 22

-- Bidi_Paired_Bracket_Type values
lu.UCDN_BIDI_PAIRED_BRACKET_TYPE_OPEN = 0
lu.UCDN_BIDI_PAIRED_BRACKET_TYPE_CLOSE = 1
lu.UCDN_BIDI_PAIRED_BRACKET_TYPE_NONE = 2

return lu
